name: Scheduled Health Check

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *" # Run every 30 minutes

jobs:
  health_check_job:
    runs-on: ubuntu-latest
    name: Check all sites
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run Health Check
        id: health_check
        run: bash ./script/health-check.sh

      - name: Run Notification
        id: notification
        env:
          HEALTH_STATUS: ${{ steps.health_check.outputs.status || 'No output' }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: bash ./script/notification.sh
